--[[
	This script has been purchased for "Admin Quick Menu" from ScriptFodder.com
	© 2017 Blt950 do not share, re-distribute or modify
	without permission.
--]]




/*

	===================================================
	=============  DO NOT EDIT THIS FILE ==============
	==== IF YOU DO, YOU LOOSE ALL SUPPORT RIGHTS!  ====
	===================================================

*/

function aqm.hasAccess(cmd)

	if aqm.adminMod == "ulx" then
		return LocalPlayer():query(cmd)

	elseif aqm.adminMod == "fadmin" then
		return FAdmin.Access.PlayerHasPrivilege(LocalPlayer(), cmd)

	end

	return false
end	

function aqm.chatMsg(string)
	chat.AddText(Color(200,100,100),"Admin Quick Menu v."..aqm.version..": "..string)
end

function string.capitalize(str)
	return (str:gsub("^%l", string.upper))
end