--[[
	This script has been purchased for "Admin Quick Menu" from ScriptFodder.com
	© 2017 Blt950 do not share, re-distribute or modify
	without permission.
--]]




/*

	===================================================
	=============  DO NOT EDIT THIS FILE ==============
	==== IF YOU DO, YOU LOOSE ALL SUPPORT RIGHTS!  ====
	===================================================

*/

function aqm.addNoneLabel(layer, check)
	if #player.GetAll() <= check then 
		layer:AddOption("(None)", function() end) 
	end
end

function aqm.showMenu()
	local menu = DermaMenu() 
	menu:AddOption("Admin Quick Menu", function() aqm.chatMsg("by Blt950. Purchased from ScriptFodder.com\nActive admin mod: "..string.upper(aqm.adminMod or "None")) end)
	menu:AddSpacer()

	if aqm.adminMod == "ulx" then
		aqm.buildULXMenu(menu)
	elseif aqm.adminMod == "fadmin" then
		aqm.buildFAMenu(menu)
	end

	menu:Open( 100, 100 )
	gui.SetMousePos( 110, 110 )
end

function aqm.hideMenu()
	CloseDermaMenus()
end
concommand.Add("+ULXqm", aqm.showMenu)
concommand.Add("-ULXqm", aqm.hideMenu)