--[[
	This script has been purchased for "Admin Quick Menu" from ScriptFodder.com
	© 2017 Blt950 do not share, re-distribute or modify
	without permission.
--]]




/*

	===================================================
	=============  DO NOT EDIT THIS FILE ==============
	==== IF YOU DO, YOU LOOSE ALL SUPPORT RIGHTS!  ====
	===================================================

*/

function aqm.hasAccess(ply, cmd)

	return true

end

hook.Add( "InitPostEntity", "aqm_load_interfaces", function()

	aqm.interfaces = aqm.interfaces or {}
	aqm.interfaces = {
		
		kick = {
			compability = "ulx",
			label = "Kick",
			icon = "icon16/error.png",
			hasAccess = aqm.hasAccess(),
			draw = {
				["ulx"] = {
					playerSelect = true,
					reasonSelect = true,
					reasonTable = ulx.common_kick_reasons,
					reasonCustom = true,
					endPointFunc = function(ply, reason) RunConsoleCommand("ulx", "kick", ply:Name(), reason) end
				}
			}
		},
		
		ban = {
			compability = "ulx",
			label = "Ban",
			icon = "icon16/exclamation.png",
			hasAccess = aqm.hasAccess(),
			draw = {
				["ulx"] = {
					playerSelect = true,
					timeSelect = true,
					reasonSelect = true,
					reasonTable = ulx.common_kick_reasons,
					reasonCustom = true,
					endPointFunc = function(ply, time, reason) RunConsoleCommand("ulx", "ban", ply:Name(), time, reason) end
				}
			}
		}

	}

end)