--[[
	This script has been purchased for "Admin Quick Menu" from ScriptFodder.com
	© 2017 Blt950 do not share, re-distribute or modify
	without permission.
--]]




/*

	===================================================
	=============  DO NOT EDIT THIS FILE ==============
	==== IF YOU DO, YOU LOOSE ALL SUPPORT RIGHTS!  ====
	===================================================

*/

function aqm.buildFAMenu(menu)

	/* KICK MENU */
	if hasAccess("kick") then

		local KICK_SUBMENU, KICK_SUBMENU_ICO = menu:AddSubMenu("Kick")
		KICK_SUBMENU_ICO:SetImage( "icon16/error.png" )

		for k,v in pairs(player.GetAll()) do
			local KICK_SUBMENUREASON = KICK_SUBMENU:AddSubMenu(v:Name())
			KICK_SUBMENUREASON:AddSpacer()
			KICK_SUBMENUREASON:AddOption("Custom reason", function()
				Derma_StringRequest( "Kick", "Write your reason to kick '"..v:Name().."'", nil, function(text) RunConsoleCommand("ulx", "kick", v:Name(), text) end, nil, "Kick" )
		 	end) 
		end
		if #player.GetAll() == 0 then KICK_SUBMENU:AddOption("(None)", function() end) end

	end

	/* BAN MENU */
	if hasAccess("ban") then

	local BAN_SUBMENU, BAN_SUBMENU_ICO = menu:AddSubMenu("Ban")
	BAN_SUBMENU_ICO:SetImage( "icon16/exclamation.png" )

		for k,v in pairs(player.GetAll()) do
			local BAN_SUBMENULENGTH = BAN_SUBMENU:AddSubMenu(v:Name())
			for x, y in ipairs(aqm.config.banLengths) do
				local BAN_SUBMENUREASON = BAN_SUBMENULENGTH:AddSubMenu(y.Str)
				BAN_SUBMENUREASON:AddSpacer()
				BAN_SUBMENUREASON:AddOption("Custom reason", function()
					Derma_StringRequest( "Ban", "Write your reason to your "..string.lower(y.Str).." ban for '"..v:Name().."'", nil, function(text) RunConsoleCommand("ulx", "ban", v:Name(), y.Len, text) end, nil, y.Str.." Ban")
			 	end) 
			end
			
		end
		aqm.addNoneLabel(BAN_SUBMENU, 0)

	end

	/* UNBAN */
	if hasAccess("ulx unban") and hasAccess("xgui_managebans") then
		menu:AddOption("Unban ...", function() RunConsoleCommand("xgui", "show", "Bans") end)
		
	end
end