--[[
	This script has been purchased for "Admin Quick Menu" from ScriptFodder.com
	© 2017 Blt950 do not share, re-distribute or modify
	without permission.
--]]




/*

	===================================================
	=============  DO NOT EDIT THIS FILE ==============
	==== IF YOU DO, YOU LOOSE ALL SUPPORT RIGHTS!  ====
	===================================================

*/

function aqm.buildULXMenu(menu)

	// ===========================
	// === KICK MENU
	// ===========================
	if aqm.hasAccess("ulx kick") then

		local SUBMENU, SUBMENU_ICO = menu:AddSubMenu("Kick")
		SUBMENU_ICO:SetImage( "icon16/error.png" )

		for k,v in pairs(player.GetAll()) do
			local SUBMENU_REASON = SUBMENU:AddSubMenu(v:Name())
			for x, y in pairs(ulx.common_kick_reasons) do
				SUBMENU_REASON:AddOption(y, function() RunConsoleCommand("ulx", "kick", v:Name(), y) end)
			end
			SUBMENU_REASON:AddSpacer()
			SUBMENU_REASON:AddOption("Custom reason", function()
				Derma_StringRequest( "Kick", "Write your reason to kick '"..v:Name().."'", nil, function(text) RunConsoleCommand("ulx", "kick", v:Name(), text) end, nil, "Kick" )
		 	end) 
		end
		aqm.addNoneLabel(SUBMENU, 0)

	end

	// ===========================
	// === BAN MENU
	// ===========================
	if aqm.hasAccess("ulx ban") then

		local SUBMENU, SUBMENU_ICO = menu:AddSubMenu("Ban")
		SUBMENU_ICO:SetImage( "icon16/exclamation.png" )

		for k,v in pairs(player.GetAll()) do
			local SUBMENU_LENGTH = SUBMENU:AddSubMenu(v:Name())
			for x, y in ipairs(aqm.config.banLengths) do
				local SUBMENU_REASON = SUBMENU_LENGTH:AddSubMenu(y.Str)
				for q, w in pairs(ulx.common_kick_reasons) do
					SUBMENU_REASON:AddOption(w, function() RunConsoleCommand("ulx", "ban", v:Name(), y.Len, w) end)
				end
				SUBMENU_REASON:AddSpacer()
				SUBMENU_REASON:AddOption("Custom reason", function()
					Derma_StringRequest( "Ban", "Write your reason to your "..string.lower(y.Str).." ban for '"..v:Name().."'", nil, function(text) RunConsoleCommand("ulx", "ban", v:Name(), y.Len, text) end, nil, y.Str.." Ban")
			 	end) 
			end
			
		end
		aqm.addNoneLabel(SUBMENU, 0)

	end

	// ===========================
	// === BAN MENU
	// ===========================
	if aqm.hasAccess("ulx unban") and aqm.hasAccess("xgui_managebans") then
		menu:AddOption("Unban ...", function() RunConsoleCommand("xgui", "show", "Bans") end)
		
	end

	





	// ###########################
	// ### TELEPORT CATEGORY
	// ###########################

	if aqm.hasAccess("ulx bring") or aqm.hasAccess("ulx goto") or aqm.hasAccess("ulx return") then

		menu:AddSpacer()
		local CATEGORY_TELEPORT, CATEGORY_TELEPORT_ICO = menu:AddSubMenu("Teleport")
		CATEGORY_TELEPORT_ICO:SetImage( "icon16/map.png" )


			// ===========================
			// === BRING MENU
			// ===========================
			if aqm.hasAccess("ulx bring") then
				local SUBMENU = CATEGORY_TELEPORT:AddSubMenu("Bring")

				for k,v in pairs(player.GetAll()) do
					if v != LocalPlayer() then
						SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "bring", v:Name()) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 1)
			end

			// ===========================
			// === GOTO MENU
			// ===========================
			if aqm.hasAccess("ulx goto") then
				local SUBMENU = CATEGORY_TELEPORT:AddSubMenu("Goto")

				for k,v in pairs(player.GetAll()) do
					if v != LocalPlayer() then
						SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "goto", v:Name()) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 1)
			end

			// ===========================
			// === RETURN MENU
			// ===========================
			if aqm.hasAccess("ulx return") then
				local SUBMENU = CATEGORY_TELEPORT:AddSubMenu("Return")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "return", v:Name()) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

	end


	// ===========================
	// === SPECTATE MENU
	// ===========================
	if aqm.hasAccess("ulx spectate") then

		local SUBMENU, SUBMENU_ICO = menu:AddSubMenu("Spectate")
		SUBMENU_ICO:SetImage( "icon16/eye.png" )

		for k,v in pairs(player.GetAll()) do
			SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "spectate", v:Name()) end)
		end

		aqm.addNoneLabel(SUBMENU, 0)

	end












	// ###########################
	// ### ADMIN CATEGORY
	// ###########################

	if aqm.hasAccess("ulx hp") or aqm.hasAccess("ulx armor") or aqm.hasAccess("ulx jail") or aqm.hasAccess("ulx mute") or aqm.hasAccess("ulx unmute") or aqm.hasAccess("ulx unjail") then

		menu:AddSpacer()
		local CATEGORY_ADMIN, CATEGORY_ADMIN_ICO = menu:AddSubMenu("Administrative")
		CATEGORY_ADMIN_ICO:SetImage( "icon16/user.png" )

			// ===========================
			// === HP MENU
			// ===========================
			if aqm.hasAccess("ulx hp") then
				local SUBMENU, SUBMENU_ICO = CATEGORY_ADMIN:AddSubMenu("Health")
				SUBMENU_ICO:SetImage( "icon16/heart.png" )

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_AMOUNT = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.defaultValues_ULX) do
						SUBMENU_AMOUNT:AddOption(y.Str, function() RunConsoleCommand("ulx", "hp", v:Name(), y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === ARMOR MENU
			// ===========================
			if aqm.hasAccess("ulx armor") then
				local SUBMENU, SUBMENU_ICO = CATEGORY_ADMIN:AddSubMenu("Armor")
				SUBMENU_ICO:SetImage( "icon16/shield.png" )

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_AMOUNT = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.defaultValues_ULX) do
						SUBMENU_AMOUNT:AddOption(y.Str, function() RunConsoleCommand("ulx", "armor", v:Name(), y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === JAIL MENU
			// ===========================
			if aqm.hasAccess("ulx jail") then
				local SUBMENU, SUBMENU_ICO = CATEGORY_ADMIN:AddSubMenu("Jail")
				SUBMENU_ICO:SetImage( "icon16/flag_red.png" )

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_TIME = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.jailValues) do
						SUBMENU_TIME:AddOption(y.Str, function() RunConsoleCommand("ulx", "jail", v:Name(), y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === MUTE MENU
			// ===========================
			if aqm.hasAccess("ulx mute") then

				local SUBMENU, SUBMENU_ICO = CATEGORY_ADMIN:AddSubMenu("Mute")
				SUBMENU_ICO:SetImage( "icon16/comment_delete.png" )

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "mute", v:Name()) end)
				end

				aqm.addNoneLabel(SUBMENU, 0)

			end
			

			CATEGORY_ADMIN:AddSpacer()

			// ===========================
			// === UN-MUTE MENU
			// ===========================
			if aqm.hasAccess("ulx unmute") then

				local SUBMENU = CATEGORY_ADMIN:AddSubMenu("Un-Mute")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "unmute", v:Name()) end)
				end

				aqm.addNoneLabel(SUBMENU, 0)

			end

			// ===========================
			// === UN-JAIL MENU
			// ===========================
			if aqm.hasAccess("ulx unjail") then

				local SUBMENU = CATEGORY_ADMIN:AddSubMenu("Un-Jail")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "unjail", v:Name()) end)
				end

				aqm.addNoneLabel(SUBMENU, 0)

			end
	end










	// ###########################
	// ### FUN CATEGORY
	// ###########################

	if aqm.hasAccess("ulx blind") or aqm.hasAccess("ulx cloak") or aqm.hasAccess("ulx freeze") or aqm.hasAccess("ulx god") or aqm.hasAccess("ulx ignite") or aqm.hasAccess("ulx maul")
		or aqm.hasAccess("ulx ragdoll") or aqm.hasAccess("ulx slap") or aqm.hasAccess("ulx slay") or aqm.hasAccess("ulx sslay") or aqm.hasAccess("ulx strip") or aqm.hasAccess("ulx whip")
		 or aqm.hasAccess("ulx uncloak") or aqm.hasAccess("ulx unfreeze") or aqm.hasAccess("ulx ungod") or aqm.hasAccess("ulx unragdoll") then

		local CATEGORY_FUN, CATEGORY_FUN_ICO = menu:AddSubMenu("Fun")
		CATEGORY_FUN_ICO:SetImage( "icon16/emoticon_smile.png" )

			// ===========================
			// === BLIND MENU
			// ===========================
			if aqm.hasAccess("ulx blind") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Blind")

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_AMOUNT = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.defaultValues_ULX) do
						SUBMENU_AMOUNT:AddOption(y.Str, function() RunConsoleCommand("ulx", "blind", v:Name(), y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === CLOAK MENU
			// ===========================
			if aqm.hasAccess("ulx cloak") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Cloak")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "cloak", v:Name(), 255 ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === FREEZE MENU
			// ===========================
			if aqm.hasAccess("ulx freeze") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Freeze")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "freeze", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end
			
			// ===========================
			// === GOD MENU
			// ===========================
			if aqm.hasAccess("ulx god") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("God")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "god", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === IGNITE MENU
			// ===========================
			if aqm.hasAccess("ulx ignite") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Ignite")

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_AMOUNT = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.igniteValues) do
						SUBMENU_AMOUNT:AddOption(y.Str, function() RunConsoleCommand("ulx", "ignite", v:Name(), y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === MAUL MENU
			// ===========================
			if aqm.hasAccess("ulx maul") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Maul")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "maul", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === RAGDOLL MENU
			// ===========================
			if aqm.hasAccess("ulx ragdoll") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Ragdoll")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "ragdoll", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === SLAP MENU
			// ===========================
			if aqm.hasAccess("ulx slap") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Slap")

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_AMOUNT = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.defaultValues_ULX) do
						SUBMENU_AMOUNT:AddOption(y.Str, function() RunConsoleCommand("ulx", "slap", v:Name(), y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === SLAY MENU
			// ===========================
			if aqm.hasAccess("ulx slay") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Slay")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "slay", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === SSLAY MENU
			// ===========================
			if aqm.hasAccess("ulx sslay") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Silent Slay")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "sslay", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === STRIP MENU
			// ===========================
			if aqm.hasAccess("ulx strip") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Strip")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "strip", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === WHIP MENU
			// ===========================
			if aqm.hasAccess("ulx whip") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Whip")

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_AMOUNT = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(aqm.config.defaultValues_ULX) do
						SUBMENU_AMOUNT:AddOption(y.Str, function() RunConsoleCommand("ulx", "whip", v:Name(), 10, y.Len) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			CATEGORY_FUN:AddSpacer()

			// ===========================
			// === UN-CLOAK MENU
			// ===========================
			if aqm.hasAccess("ulx uncloak") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Un-Cloak")
				for k,v in pairs(player.GetAll()) do

					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "uncloak", v:Name(), 255 ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === UN-FREEZE MENU
			// ===========================
			if aqm.hasAccess("ulx unfreeze") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Un-Freeze")
				for k,v in pairs(player.GetAll()) do

					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "unfreeze", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === UN-GOD MENU
			// ===========================
			if aqm.hasAccess("ulx ungod") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Un-God")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "ungod", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === UN-RAGDOLL MENU
			// ===========================
			if aqm.hasAccess("ulx unragdoll") then
				local SUBMENU = CATEGORY_FUN:AddSubMenu("Un-Ragdoll")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "unragdoll", v:Name() ) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

	end









	// ###########################
	// ### RCON CATEGORY
	// ###########################

	menu:AddSpacer()

	if aqm.hasAccess("ulx cexec") or aqm.hasAccess("ulx luarun") or aqm.hasAccess("ulx rcon") then
		
		local CATEGORY_RCON, CATEGORY_RCON_ICO = menu:AddSubMenu("Rcon")
		CATEGORY_RCON_ICO:SetImage( "icon16/application_xp_terminal.png" )

			// ===========================
			// === CEXEC MENU
			// ===========================
			if aqm.hasAccess("ulx cexec") then
				local SUBMENU = CATEGORY_RCON:AddSubMenu("Cexec")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() 
						Derma_StringRequest( "CEXEC", "Write your command to run on "..v:Name(), nil, function(text) RunConsoleCommand("ulx", "cexec", v:Name(), text) end, function() end )
					end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === LUARUN MENU
			// ===========================
			if aqm.hasAccess("ulx luarun") then
				CATEGORY_RCON:AddOption("Luarun", function()
					Derma_StringRequest( "LUARUN", "Write your command to luarun", nil, function(text) RunConsoleCommand("ulx", "luarun", text) end, function() end )
				end)
			end

			// ===========================
			// === RCON MENU
			// ===========================
			if aqm.hasAccess("ulx rcon") then
				CATEGORY_RCON:AddOption("Rcon", function()
					Derma_StringRequest( "RCON", "Write your command to RCON", nil, function(text) RunConsoleCommand("ulx", "rcon", text) end, function() end )
				end)
			end

	end









	// ###########################
	// ### ACCESS CATEGORY
	// ###########################

	if aqm.hasAccess("ulx adduser") or aqm.hasAccess("ulx removeuser") then

		local CATEGORY_ACCESS, CATEGORY_ACCESS_ICO = menu:AddSubMenu("Access")
		CATEGORY_ACCESS_ICO:SetImage( "icon16/key.png" )

			// ===========================
			// === ADDUSER MENU
			// ===========================
			if aqm.hasAccess("ulx adduser") then
				local SUBMENU = CATEGORY_ACCESS:AddSubMenu("Add User")

				for k,v in pairs(player.GetAll()) do
					local SUBMENU_GROUP = SUBMENU:AddSubMenu(v:Name())
					for x, y in ipairs(xgui.data.groups) do
						SUBMENU_GROUP:AddOption(string.capitalize(y), function() RunConsoleCommand("ulx", "adduser", v:Name(), y) end)
					end
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end

			// ===========================
			// === REMOVEUSER MENU
			// ===========================
			if aqm.hasAccess("ulx removeuser") then
				local SUBMENU = CATEGORY_ACCESS:AddSubMenu("Remove User")

				for k,v in pairs(player.GetAll()) do
					SUBMENU:AddOption(v:Name(), function() RunConsoleCommand("ulx", "removeuser", v:Name()) end)
				end
				aqm.addNoneLabel(SUBMENU, 0)
			end
	end



end // End of build function